@startuml

package "System Interface Library" {
	package "Time" {
		component [External Watchdog Timer] as EWDG
		component [Task Timer] as TaskTimer
		component [Real-Time Clock] as RTCI
	}
	package "Memory" {
		component [EEPROM] as EEPROM
		component [SDMMC] as SDMMCI
		component [Filesystem] as Filesystem
		component [Configuration Registry] as ConfigReg
	}
	package "I/O" {
		component [ADC] as ADCI
		component [PWM] as PWMI
		component [Multipurpose I/O] as MPIO
	}
	package "Communication Interfaces" {
		component [CAN Interface] as CANI
		component [UART Interface] as UARTI
		component [I2C Interface] as I2CI
		component [SPI Interface] as SPII
	}
}

@enduml
