TARGET=TestVehicleInterface

MOCKS=\
	mock/lib/logging/MockLogging.c \
	mock/time/tasktimer/MockTaskTimer.c

TESTED_SRC=../Application/vehicleInterface/vehicleState/vehicleState.c

TEST_SRC=vehicleInterface/vehicleState/TestVehicleState.c

# Fetch the build instructions
TEST_ROOT=../../..
include $(TEST_ROOT)/test_common.mk