name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      uses: carlosperate/arm-none-eabi-gcc-action@v1.8.1
      with:
        release: '13.2.Rel1' # version of arm-none-eabi-gcc
      run: ./firmware/build.sh
    - name: Test
      run: ./firmware/test/run_tests.sh
