name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '13.2.Rel1'
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: ./firmware/build.sh
    - name: Test
      run: ./firmware/test/run_tests.sh
